defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  username: aojcqngqbefwmn
  password: KT_mIgPXa3D2QRFWwl9oUSIs6R

store: &store
  host: ec2-54-243-238-144.compute-1.amazonaws.com
  port: 5432

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter:  postgresql
  encoding: unicode
  pool: 5
  database: db16nhata1slfe
  username: cmrlscevzadons
  password: qNRj8PncT7yPak9sJf8tpnfPcU
  host: ec2-23-23-81-171.compute-1.amazonaws.com
  Psql: heroku pg:psql --app bindus HEROKU_POSTGRESQL_MAROON
  URL:  postgres://cmrlscevzadons:qNRj8PncT7yPak9sJf8tpnfPcU@ec2-23-23-81-171.compute-1.amazonaws.com:5432/db16nhata1slfe
  port: 5432

# production:  
  # <<: *defaults
  # <<: *store
  # database: d9hqk0dtokmtui
  # pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000